### ISSUE TITLE
A linux version?

### ISSUE THREAD

**Issue by MastaG** [Matviy/nvidia-NVENC-multi-session-patch#2]
A linux version would be highly appreciated..
This way I could just get a gtx1050 and enable unlimited transcoding sessions for my plex server..

**Comment by trustfarm-dev** [comment]
refer https://github.com/keylase/nvidia-patch

**Comment by Matviy** [comment]
Thanks @trustfarm-dev , it appears a user-friendly Linux version has already been created.
